# Generated by Django 4.1.7 on 2024-12-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_service_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barber',
            new_name='BarberItem',
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceItem',
        ),
    ]
