# Generated by Django 4.1.7 on 2024-12-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_barber_barberitem_rename_service_serviceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberitem',
            name='available_slots',
        ),
    ]
