# Generated by Django 4.1.7 on 2024-12-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_barberitem_available_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.barberitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.serviceitem')),
            ],
            options={
                'unique_together': {('barber', 'date', 'time')},
            },
        ),
    ]
